# Build setup for Travis CI

language:
  - java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

addons:
  sonarcloud:
    organization: adamcarroll-github
    token:
        secure: "novZAtL8WmZQD5IOaOAFAFWm7ohdkT3omGvMgg1cO0w6f7ct0O4CXSmMsneDAfYBHI2S/crTnRxnU/u6cdgb6sMeGI/P/7Qtmc7LGQgDB0sPN0uOLE4J3K1t2p8FEEXVAzDkZR5KUkO/VxuHJYm3oArPZoejNnYQVh3EmAmtZTlBkE6nbkO4fkqmmAb1wzRzetypowv99PjhXiWXX5GsHFupwCrm0Y59yfE9DQNeg8HUSe8IXjC6l5b6WfX3wiK6YHuhAan9MqcsuoDLRQp39z404c3p0ZBfG0D6TOb1Sfkks/k1VwDZs5Rpua9Qn6GYPxQBXYSYjLCaTH9j8bi14EHfmujFOx88dcHru48BbwGvQAh2kKypVIGeY6fQUwaJb+yu92ZVPEmNOtaUlIoz76RcbwC/oC7ZJwMfx7sk/mlclYiaXcLfiy4iagLMEvdNMwx6iKRXukGWVoBTxkmfIqjGTUqzb4biS1JkbA6XbjySAQ5kRMBtZZIPRYbtc6BtvJJ8+vOUWxVNv0DlB0iHdJCT7LcKDWcAn09/leOpFeE2L22pu8QeNo/2bDokv4H7LZQPwRVabhJG+vT+/K2vWBbwbC2ND20VuCmWD0zaCV6Va0Biw/nVcJ9fDKDtFK+7iZtvQ7wod7x61rBONjyP+VvRWhdyyQEmjTbT3yof2Gw="
    branches:
      - master
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache

install: true

script:
  - ./gradlew clean build jacocoTestReport jfxNative sonarqube -info

deploy:
  provider: releases
  api_key:
    secure: Wlf91YmRm+lGVe3KtUb8n1RGGgRGmCalgc0K2q1OphmgSAsMHGj5xtohHPTDL4pY7t4MbvC6X4fzrhVIs/BytweMXXp4nzHFL4RAs5NLxdyQ4DYsI6kIWm6qqUjSudrZ2nbuXu2RS1guzQbvUq9qqgGDGhDVkcQVqkq0K5vmoNh5IMPdxtJ3BzJAdD/99zkh1RIfeoVw1sbmUBhRI888yfpIJ1JcTDWUtDXwrWCPAgpjkT6J15+0LdrTgekwfO+SaWlRalReVrubXYRo8mH6auwwiocTwKoJYNAoYQgX7YQSyVbMjx1YTnU2+v5K/V4MRrmPc9TiphETcHCvJWCTDvjMJ1GUOZoJmMmQ7548iyJkTaLvZX6z0NfwsJZ9FIGxFdWjKFD2FEW9uM0DfJCr6Zi8PzCUob/Db4Yt5/kN8QdRs1uYH09n8BxEjh9fOlHZh3BxUznMV/g7iqRARo7Wg8JLk0/FmLggL9ZfnKyXv9HphY2YRbeWW0/MHW03/O6UQVwWEIFZuQwVzNHxUZEDmh8Gj29YalTQv8EzOOhtRDgiXNTtGNPp9qgHGP0pxu6dX+Hr8Q84EUvKPJQdxXkcs0j36kAWE5/X/07BIcC8rnsNACjCzMeXqGJP+1u1T6nvZ9HNAQMCOHFbi+wXyz7FrVO3zYDN66YfWkMDNJ8OQ9A=
  file:
    - "gui/build/distributions/VocabHunter-${TRAVIS_TAG}.zip"
    - "package/build/jfx/native/vocabhunter-${TRAVIS_TAG}.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: AdamCarroll/vh-sandbox
