# Build setup for Travis CI

language:
  - java

os:
  - osx

osx_image:
  - xcode7.2

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - ./gradlew clean build -info
